### ISSUE TITLE
Enhancement Request for Intune Audit Dashboard Workbook - Add User Audit

### ISSUE THREAD

**Issue by tgeske88** [MSEndpointMgr/Reporting#15]
In the Intune Audit Dashboard workbook, would it be possible for you to add another drop down column that's named 'User' and filters for only newly created/disabled/deleted users (and guest accounts)? Thinking out loud, maybe even expand on this idea and add group membership changes as well?

![image](https://user-images.githubusercontent.com/48250032/199320665-cb4510d3-f2fb-436f-bedc-30689937628c.png)

This workbook gives such visibility for devices/apps but it's lacking user/group auditing (which would be awesome to see)!

**Comment by JankeSkanke** [comment]
This is a audit workbook based on Intune audit logs. What you are requesting is based on Azure AD Audit logs and will not be a part of this Solution. In many cases the Intune admin will not, and should not have access to Azure AD Logs.
